name: Integrate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: holepunchto/actions/node-base@v1
      - run: npm run lint
  prebuild:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
            arch: x64
          - os: ubuntu-22.04-arm
            platform: linux
            arch: arm64
          - os: ubuntu-24.04
            platform: android
            arch: x64
          - os: ubuntu-24.04
            platform: android
            arch: ia32
          - os: ubuntu-24.04
            platform: android
            arch: arm64
          - os: ubuntu-24.04
            platform: android
            arch: arm
          - os: macos-14
            platform: darwin
            arch: x64
          - os: macos-14
            platform: darwin
            arch: arm64
          - os: macos-14
            platform: ios
            arch: arm64
          - os: macos-14
            platform: ios
            arch: arm64
            tags: -simulator
            flags: --simulator
          - os: macos-14
            platform: ios
            arch: x64
            tags: -simulator
            flags: --simulator
          - os: windows-2022
            platform: win32
            arch: x64
          - os: windows-2022
            platform: win32
            arch: arm64
    runs-on: ${{ matrix.os }}
    name: Build / ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - uses: holepunchto/actions/setup-llvm@v1
      - uses: holepunchto/actions/setup-nasm@v1
        if: ${{ matrix.platform == 'win32' }}
      - uses: holepunchto/actions/compile-prebuilds@v1
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          flags: ${{ matrix.flags }}
          tags: ${{ matrix.tags}}
          upload: true
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: darwin
          - os: windows-latest
            platform: win32
    runs-on: ${{ matrix.os }}
    needs: prebuild
    name: Test / ${{ matrix.platform }}
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - uses: holepunchto/actions/download-prebuilds@v1
        with:
          prefix: npm
      - run: npm test
